name: Valist Publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: valist-io/valist-github-action@v2.3.1
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          account: jiyuu-jin
          project: akashictech.io
          release: ${{ env.TIMESTAMP }}
          path: undefined
